apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-demo-app
  labels:
    app: cicd-demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicd-demo-app
  template:
    metadata:
      labels:
        app: cicd-demo-app
    spec:
      containers:
      - name: web-app
        image: DOCKER_IMAGE_PLACEHOLDER
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cicd-demo-service
spec:
  type: LoadBalancer
  selector:
    app: cicd-demo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
